### ISSUE TITLE
Used pins not matching pictures

### ISSUE THREAD

**Issue by micheld93** [kasik96/esp8266-vindriktning-particle-sensor-homekit#8]
Hi, 

the picture shows that the TX-pin is used (Wemos) but the text mentioned that D2 is to be used. What is right?

**Comment by Z-Beeblebrox1978** [comment]
According to SerialCom.h file (which you can find in your sketch) Arduino should received data from sensor on GPIO04 which is pin D2

**Comment by micheld93** [comment]
Your are right. It needs to be D2.
